version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
      - task-service
    environment:
      - PORT=3001
      - AUTH_SERVICE_URL=http://auth-service:4000
      - TASK_SERVICE_URL=http://task-service:5000
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/pomodoro-auth
      - JWT_SECRET=your_jwt_secret_key_here
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_email_password
      - FRONTEND_URL=http://localhost:3000
    networks:
      - app-network

  task-service:
    build: ./task-service
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - auth-service
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/pomodoro-tasks
      - AUTH_SERVICE_URL=http://auth-service:4000
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: